### ISSUE TITLE
Can this be used on the CD-I console?

### ISSUE THREAD

**Issue by zezba9000** [n6il/MicrowareCCC#1]
I've been looking for the OS-9 Microware C Compiler v3.2 for CD-I and can't find it anywhere online.

So fishing for what resources to use on the CD-I for homebrew.

Is this the 3.2 version that can be used for the CD-I dev?

**Comment by n6il** [comment]
CD-I is a OS-9/68K system is it not?  This compiler is for OS-9/6809 or NitrOS9.

**Comment by zezba9000** [comment]
Yes I think you're correct. Sadly the original compiler is impossible to find from what I can tell.
